---
language: python
python: "2.7"

install:
  - pip install ansible
  - ln -s . vagrant
  - echo "[default]\nroles_path = ." > ansible.cfg

script:
  - ansible-playbook playbook.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
