---
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"

- name: ensure vim is installed
  package:
    name: "{{ item }}"
  with_items: "{{ vim_packages }}"

- include: config.yml
